language: c
compiler:
  - gcc
  - clang

before_script:
# installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make check -j3
  - sudo make install
  - cd ..
# installing libconfig, needed for DHT_bootstrap_daemon
  - wget http://www.hyperrealm.com/libconfig/libconfig-1.4.9.tar.gz
  - tar -xvzf libconfig-1.4.9.tar.gz
  - cd libconfig-1.4.9
  - ./configure && make -j3
  - sudo make install
  - cd ..
# installing libopus, needed for audio encoding/decoding
  - wget http://downloads.xiph.org/releases/opus/opus-1.0.3.tar.gz
  - tar xzvf opus-1.0.3.tar.gz
  - cd opus-1.0.3
  - ./configure && make -j3
  - sudo make install
  - cd ..
# installing libsdl1.2, needed for displaying video frames
  - wget http://www.libsdl.org/release/SDL-1.2.15.tar.gz
  - tar -xvzf SDL-1.2.15.tar.gz
  - cd SDL-1.2.15
  - ./configure && make -j3
  - sudo make install
  - cd ..
# installing libopenal, needed for audio capture/playback
  - sudo apt-get install libopenal-dev
# installing yasm, needed for compiling ffmpeg
  - sudo apt-get install yasm
# installing ffmpeg, needed for capturing and encoding/decoding video
  - wget https://www.ffmpeg.org/releases/ffmpeg-2.0.2.tar.gz
  - tar -xvzf ffmpeg-2.0.2.tar.gz
  - cd ffmpeg-2.0.2
  - ./configure && make -j3
  - sudo make install
  - cd ..
# creating librarys' links and updating cache
  - sudo ldconfig
# installing check, needed for unit tests
  - sudo apt-get install check

script:
  - autoreconf -i
  - ./configure
  - make -j3
  - make check
  - make dist

notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
