language: c
compiler:
  - gcc
  - clang

before_script:
# installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make check -j3
  - sudo make install
  - cd ..
# installing libconfig, needed for DHT_bootstrap_daemon
  - wget http://www.hyperrealm.com/libconfig/libconfig-1.4.9.tar.gz
  - tar -xvzf libconfig-1.4.9.tar.gz
  - cd libconfig-1.4.9
  - ./configure && make -j3
  - sudo make install
  - cd ..
# installing libopus, libvpx, libopenal, libsdl and ffmpeg
  - sudo apt-get install libopus-dev libvpx-dev libopenal-dev libsdl1.2-dev
  - wget https://www.ffmpeg.org/releases/ffmpeg-2.0.2.tar.gz
  - tar -xvzf ffmpeg-2.0.2.tar.gz
  - cd ffmpeg-2.0.2
  - ./configure && make -j3
  - sudo make install
  - cd ..
# creating librarys' links and updating cache
  - sudo ldconfig
# installing check, needed for unit tests
  - sudo apt-get install check

script:
  - autoreconf -i
  - ./configure
  - make -j3
  - make check
  - make dist

notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
