language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - yasm
    - check

before_script:
  #installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - cd libsodium
  - git checkout tags/1.0.3 > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure > /dev/null
  - make check -j3 > /dev/null
  - sudo make install >/dev/null
  - cd ..
  #installing libconfig, needed for DHT_bootstrap_daemon
  - wget http://www.hyperrealm.com/libconfig/libconfig-1.4.9.tar.gz > /dev/null
  - tar -xvzf libconfig-1.4.9.tar.gz > /dev/null
  - cd libconfig-1.4.9
  - ./configure > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - cd ..
  #installing libopus, needed for audio encoding/decoding
  - wget http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz > /dev/null
  - tar xzf opus-1.1.tar.gz > /dev/null
  - cd opus-1.1
  - ./configure > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - cd ..
  #installing vpx
  - git clone https://chromium.googlesource.com/webm/libvpx > /dev/null
  - cd libvpx
  - git checkout tags/v1.3.0
  - ./configure --enable-shared > /dev/null
  - make -j3 >/dev/null
  - sudo make install > /dev/null
  - cd ..
  #creating libraries links and updating cache
  - sudo ldconfig > /dev/null
  #installing check, needed for unit tests
  - sudo apt-get install check > /dev/null

script:
  - autoreconf -i
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox
  - make -j3
  - make check
  - make dist

notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
