sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang
env:
  - RUN_TESTS=false
  - RUN_TESTS=true
matrix:
  allow_failures:
      - env: RUN_TESTS=true

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libconfig-dev libvpx-dev libopus-dev check -qq
  # install sodium, as it's not in Ubuntu Trusty
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - cd libsodium
  - git checkout tags/1.0.8 > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure > /dev/null
  - make -j3  >/dev/null
  - sudo make install >/dev/null
  - cd ..
  - sudo ldconfig

script:
  - ./autogen.sh
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox
  - make
  - if [ "$RUN_TESTS" = "true" ]; then make check; fi
  - if [ "$RUN_TESTS" = "true" ]; then cat build/test-suite.log; fi
  - make dist

notifications:
  email: false

  irc:
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
